dist: trusty
sudo: required
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - python3
      - python3-dev 

script:
  - make
  - sudo make install
  - make test

