site_name: libspot
site_url: https://asiffer.github.io/libspot/
repo_url: https://github.com/asiffer/libspot
repo_name: asiffer/libspot

theme:
  name: shadcn
  icon: img/logo.svg
  favicon: img/favicon.ico
  katex_options:
    macros:
      "\\KK": "\\mathop{\\mathrm{K}}"

nav:
  - index.md
  - about.md
  - install.md
  - get_started.md
  - parameters.md
  - api.md
  - Foreign languages:
      - foreign/python.md
      - foreign/javascript.md
      - foreign/golang.md
      - foreign/rust.md
      - foreign/performances.md
  - Internals:
      - internals/spot.md
      - internals/fit.md
      - internals/math.md



watch:
  - benchmark
  - src
  - include

plugins:
  - search
  

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.tab
  - pymdownx.snippets:
      url_download: true
  - shadcn.extensions.iconify
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
