site_name: libspot
repo_url: https://github.com/asiffer/libspot
repo_name: asiffer/libspot

theme:
  name: shadcn
  icon: https://raw.githubusercontent.com/asiffer/libspot/refs/heads/master/docs/img/logo.svg
  katex_options:
    macros:
      "\\KK": "\\mathop{\\mathrm{K}}"

watch:
  - benchmark
  - src
  - include

plugins:
  - search
  


markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.tab
  - pymdownx.snippets:
      url_download: true
  - shadcn.extensions.iconify
  - shadcn.extensions.codexec
  - shadcn.extensions.echarts.alpha
