# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libstream', [dirname(__file__)])
        except ImportError:
            import _libstream
            return _libstream
        if fp is not None:
            try:
                _mod = imp.load_module('_libstream', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libstream = swig_import_helper()
    del swig_import_helper
else:
    import _libstream
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _libstream.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _libstream.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _libstream.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _libstream.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _libstream.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _libstream.SwigPyIterator_equal(self, x)

    def copy(self):
        return _libstream.SwigPyIterator_copy(self)

    def next(self):
        return _libstream.SwigPyIterator_next(self)

    def __next__(self):
        return _libstream.SwigPyIterator___next__(self)

    def previous(self):
        return _libstream.SwigPyIterator_previous(self)

    def advance(self, n):
        return _libstream.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _libstream.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _libstream.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _libstream.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _libstream.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _libstream.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _libstream.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _libstream.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _libstream.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _libstream.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _libstream.DoubleVector___bool__(self)

    def __len__(self):
        return _libstream.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _libstream.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _libstream.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _libstream.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _libstream.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _libstream.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _libstream.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _libstream.DoubleVector_pop(self)

    def append(self, x):
        return _libstream.DoubleVector_append(self, x)

    def empty(self):
        return _libstream.DoubleVector_empty(self)

    def size(self):
        return _libstream.DoubleVector_size(self)

    def swap(self, v):
        return _libstream.DoubleVector_swap(self, v)

    def begin(self):
        return _libstream.DoubleVector_begin(self)

    def end(self):
        return _libstream.DoubleVector_end(self)

    def rbegin(self):
        return _libstream.DoubleVector_rbegin(self)

    def rend(self):
        return _libstream.DoubleVector_rend(self)

    def clear(self):
        return _libstream.DoubleVector_clear(self)

    def get_allocator(self):
        return _libstream.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _libstream.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _libstream.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _libstream.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _libstream.DoubleVector_push_back(self, x)

    def front(self):
        return _libstream.DoubleVector_front(self)

    def back(self):
        return _libstream.DoubleVector_back(self)

    def assign(self, n, x):
        return _libstream.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _libstream.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _libstream.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _libstream.DoubleVector_reserve(self, n)

    def capacity(self):
        return _libstream.DoubleVector_capacity(self)
    __swig_destroy__ = _libstream.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _libstream.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class Ubend(DoubleVector):
    __swig_setmethods__ = {}
    for _s in [DoubleVector]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ubend, name, value)
    __swig_getmethods__ = {}
    for _s in [DoubleVector]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Ubend, name)
    __repr__ = _swig_repr

    def __init__(self, N=-1):
        this = _libstream.new_Ubend(N)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def merge(self, U):
        return _libstream.Ubend_merge(self, U)

    def getCursor(self):
        return _libstream.Ubend_getCursor(self)

    def getLastErasedData(self):
        return _libstream.Ubend_getLastErasedData(self)

    def push(self, x):
        return _libstream.Ubend_push(self, x)

    def getCapacity(self):
        return _libstream.Ubend_getCapacity(self)

    def isFilled(self):
        return _libstream.Ubend_isFilled(self)
    __swig_destroy__ = _libstream.delete_Ubend
    __del__ = lambda self: None
Ubend_swigregister = _libstream.Ubend_swigregister
Ubend_swigregister(Ubend)

class StreamMean(Ubend):
    __swig_setmethods__ = {}
    for _s in [Ubend]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamMean, name, value)
    __swig_getmethods__ = {}
    for _s in [Ubend]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StreamMean, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _libstream.new_StreamMean(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def mean(self):
        return _libstream.StreamMean_mean(self)

    def step(self, x_n):
        return _libstream.StreamMean_step(self, x_n)

    def __add__(self, other):
        return _libstream.StreamMean___add__(self, other)
    __swig_destroy__ = _libstream.delete_StreamMean
    __del__ = lambda self: None
StreamMean_swigregister = _libstream.StreamMean_swigregister
StreamMean_swigregister(StreamMean)

class StreamVar(StreamMean):
    __swig_setmethods__ = {}
    for _s in [StreamMean]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamVar, name, value)
    __swig_getmethods__ = {}
    for _s in [StreamMean]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StreamVar, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _libstream.new_StreamVar(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def var(self):
        return _libstream.StreamVar_var(self)

    def step(self, x_n):
        return _libstream.StreamVar_step(self, x_n)
    __swig_destroy__ = _libstream.delete_StreamVar
    __del__ = lambda self: None
StreamVar_swigregister = _libstream.StreamVar_swigregister
StreamVar_swigregister(StreamVar)

class StreamMoments(StreamVar):
    __swig_setmethods__ = {}
    for _s in [StreamVar]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamMoments, name, value)
    __swig_getmethods__ = {}
    for _s in [StreamVar]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StreamMoments, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _libstream.new_StreamMoments(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def skew(self):
        return _libstream.StreamMoments_skew(self)

    def step(self, x_n):
        return _libstream.StreamMoments_step(self, x_n)
    __swig_destroy__ = _libstream.delete_StreamMoments
    __del__ = lambda self: None
StreamMoments_swigregister = _libstream.StreamMoments_swigregister
StreamMoments_swigregister(StreamMoments)

class StreamStats(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StreamStats, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StreamStats, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _libstream.new_StreamStats(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def merge(self, S):
        return _libstream.StreamStats_merge(self, S)

    def get_s_star(self):
        return _libstream.StreamStats_get_s_star(self)

    def size(self):
        return _libstream.StreamStats_size(self)

    def bimodalTest(self):
        return _libstream.StreamStats_bimodalTest(self)

    def step(self, x):
        return _libstream.StreamStats_step(self, x)

    def __lt__(self, other):
        return _libstream.StreamStats___lt__(self, other)

    def stringStatus(self):
        return _libstream.StreamStats_stringStatus(self)
    __swig_destroy__ = _libstream.delete_StreamStats
    __del__ = lambda self: None
StreamStats_swigregister = _libstream.StreamStats_swigregister
StreamStats_swigregister(StreamStats)

# This file is compatible with both classic and new-style classes.


