name=Spot
version=3.0.0
author=Alban Siffer <31479857+asiffer@users.noreply.github.com>
maintainer=Alban Siffer <31479857+asiffer@users.noreply.github.com>
sentence=Born to flag outliers (from arduino)
paragraph=Spot algorithm that detects anomalies in streaming data
category=Data Processing
url=https://github.com/asiffer/libspot/
architectures=*
