name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/*.c"
      - "include/*.h"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: sudo apt update -y && sudo apt install -y build-essential

      - name: Build shared library
        run: make

      - name: Build static library
        run: make static

      - name: Put full version in env
        run: echo "VERSION_FULL=$(make version_full)" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes ""
          --draft
      - name: Upload artifact to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          "$GITHUB_REF_NAME" dist/libspot**
          --repo "$GITHUB_REPOSITORY"
