name: release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt update -y && sudo apt install -y build-essential

      - name: Build shared library
        run: make

      - name: Build static library
        run: make static

      - name: Release now
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          title: "New release"
          files: |
            lib/libspot.so*
            lib/libspot.a*
