name: release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"
      - "debian/**"
      - "snap/**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: sudo apt update -y && sudo apt install -y build-essential

      - name: Build shared library
        run: make

      - name: Build static library
        run: make static

      - name: Put full version in env
        run: echo "VERSION_FULL=$(make version_full)" >> $GITHUB_ENV

      - name: Release now
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "v${{ env.VERSION_FULL }}"
          title: "v${{ env.VERSION_FULL }}"
          files: |
            dist/libspot.so*
            dist/libspot.a*
